// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: admin.proto

package pbx

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AccountState defines possible states for a user account.
type AccountState int32

const (
	// Default state for unspecified values.
	AccountState_ACCOUNT_STATE_UNSPECIFIED AccountState = 0
	// Normal active account.
	AccountState_ACCOUNT_STATE_NORMAL AccountState = 1
	// Suspended account with limited functionality.
	AccountState_ACCOUNT_STATE_SUSPENDED AccountState = 2
)

// Enum value maps for AccountState.
var (
	AccountState_name = map[int32]string{
		0: "ACCOUNT_STATE_UNSPECIFIED",
		1: "ACCOUNT_STATE_NORMAL",
		2: "ACCOUNT_STATE_SUSPENDED",
	}
	AccountState_value = map[string]int32{
		"ACCOUNT_STATE_UNSPECIFIED": 0,
		"ACCOUNT_STATE_NORMAL":      1,
		"ACCOUNT_STATE_SUSPENDED":   2,
	}
)

func (x AccountState) Enum() *AccountState {
	p := new(AccountState)
	*p = x
	return p
}

func (x AccountState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AccountState) Descriptor() protoreflect.EnumDescriptor {
	return file_admin_proto_enumTypes[0].Descriptor()
}

func (AccountState) Type() protoreflect.EnumType {
	return &file_admin_proto_enumTypes[0]
}

func (x AccountState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AccountState.Descriptor instead.
func (AccountState) EnumDescriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{0}
}

// User represents a user account.
type User struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	UserId string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Timestamp of the last time the user was seen online.
	LastSeen *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	// Public information about the user. JSON string.
	Public        string `protobuf:"bytes,3,opt,name=public,proto3" json:"public,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *User) GetLastSeen() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeen
	}
	return nil
}

func (x *User) GetPublic() string {
	if x != nil {
		return x.Public
	}
	return ""
}

// Request to promote a user to ROOT authentication level.
type MakeUserRootRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// User ID to be promoted to ROOT.
	UserId        string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MakeUserRootRequest) Reset() {
	*x = MakeUserRootRequest{}
	mi := &file_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MakeUserRootRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MakeUserRootRequest) ProtoMessage() {}

func (x *MakeUserRootRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MakeUserRootRequest.ProtoReflect.Descriptor instead.
func (*MakeUserRootRequest) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{1}
}

func (x *MakeUserRootRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// Response to a request to promote a user to ROOT authentication level.
type MakeUserRootResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MakeUserRootResponse) Reset() {
	*x = MakeUserRootResponse{}
	mi := &file_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MakeUserRootResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MakeUserRootResponse) ProtoMessage() {}

func (x *MakeUserRootResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MakeUserRootResponse.ProtoReflect.Descriptor instead.
func (*MakeUserRootResponse) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{2}
}

// Request to retrieve user information.
type GetUserRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// User ID to retrieve information for.
	UserId        string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// Request to update a user's account state.
type UpdateUserStateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// User ID to update.
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// New account state (normal, suspended).
	State         AccountState `protobuf:"varint,2,opt,name=state,proto3,enum=pbx.AccountState" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserStateRequest) Reset() {
	*x = UpdateUserStateRequest{}
	mi := &file_admin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserStateRequest) ProtoMessage() {}

func (x *UpdateUserStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserStateRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserStateRequest) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateUserStateRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateUserStateRequest) GetState() AccountState {
	if x != nil {
		return x.State
	}
	return AccountState_ACCOUNT_STATE_UNSPECIFIED
}

// Response to a request to update a user's account state.
type UpdateUserStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserStateResponse) Reset() {
	*x = UpdateUserStateResponse{}
	mi := &file_admin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserStateResponse) ProtoMessage() {}

func (x *UpdateUserStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserStateResponse.ProtoReflect.Descriptor instead.
func (*UpdateUserStateResponse) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{5}
}

// Request to delete a user account.
type DeleteUserRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// User ID to delete.
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Whether to perform a hard delete.
	Hard          bool `protobuf:"varint,2,opt,name=hard,proto3" json:"hard,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserRequest) Reset() {
	*x = DeleteUserRequest{}
	mi := &file_admin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserRequest) ProtoMessage() {}

func (x *DeleteUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DeleteUserRequest) GetHard() bool {
	if x != nil {
		return x.Hard
	}
	return false
}

// Response to a request to delete a user account.
type DeleteUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserResponse) Reset() {
	*x = DeleteUserResponse{}
	mi := &file_admin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserResponse) ProtoMessage() {}

func (x *DeleteUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserResponse.ProtoReflect.Descriptor instead.
func (*DeleteUserResponse) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{7}
}

// Request to create a new group chat.
type CreateGroupChatRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Create a new group chat on behalf of the user.
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Name of the chat.
	ChatName      string `protobuf:"bytes,2,opt,name=chat_name,json=chatName,proto3" json:"chat_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGroupChatRequest) Reset() {
	*x = CreateGroupChatRequest{}
	mi := &file_admin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGroupChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGroupChatRequest) ProtoMessage() {}

func (x *CreateGroupChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGroupChatRequest.ProtoReflect.Descriptor instead.
func (*CreateGroupChatRequest) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{8}
}

func (x *CreateGroupChatRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateGroupChatRequest) GetChatName() string {
	if x != nil {
		return x.ChatName
	}
	return ""
}

// Response to a request to create a new group chat.
type CreateGroupChatResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Topic ID of the newly created group chat.
	TopicId       string `protobuf:"bytes,1,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGroupChatResponse) Reset() {
	*x = CreateGroupChatResponse{}
	mi := &file_admin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGroupChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGroupChatResponse) ProtoMessage() {}

func (x *CreateGroupChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGroupChatResponse.ProtoReflect.Descriptor instead.
func (*CreateGroupChatResponse) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{9}
}

func (x *CreateGroupChatResponse) GetTopicId() string {
	if x != nil {
		return x.TopicId
	}
	return ""
}

var File_admin_proto protoreflect.FileDescriptor

const file_admin_proto_rawDesc = "" +
	"\n" +
	"\vadmin.proto\x12\x03pbx\x1a\vmodel.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"p\n" +
	"\x04User\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x127\n" +
	"\tlast_seen\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\blastSeen\x12\x16\n" +
	"\x06public\x18\x03 \x01(\tR\x06public\".\n" +
	"\x13MakeUserRootRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\x16\n" +
	"\x14MakeUserRootResponse\")\n" +
	"\x0eGetUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"Z\n" +
	"\x16UpdateUserStateRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12'\n" +
	"\x05state\x18\x02 \x01(\x0e2\x11.pbx.AccountStateR\x05state\"\x19\n" +
	"\x17UpdateUserStateResponse\"@\n" +
	"\x11DeleteUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04hard\x18\x02 \x01(\bR\x04hard\"\x14\n" +
	"\x12DeleteUserResponse\"N\n" +
	"\x16CreateGroupChatRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tchat_name\x18\x02 \x01(\tR\bchatName\"4\n" +
	"\x17CreateGroupChatResponse\x12\x19\n" +
	"\btopic_id\x18\x01 \x01(\tR\atopicId*d\n" +
	"\fAccountState\x12\x1d\n" +
	"\x19ACCOUNT_STATE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14ACCOUNT_STATE_NORMAL\x10\x01\x12\x1b\n" +
	"\x17ACCOUNT_STATE_SUSPENDED\x10\x022\xe3\x02\n" +
	"\fAdminService\x12E\n" +
	"\fMakeUserRoot\x12\x18.pbx.MakeUserRootRequest\x1a\x19.pbx.MakeUserRootResponse\"\x00\x12+\n" +
	"\aGetUser\x12\x13.pbx.GetUserRequest\x1a\t.pbx.User\"\x00\x12N\n" +
	"\x0fUpdateUserState\x12\x1b.pbx.UpdateUserStateRequest\x1a\x1c.pbx.UpdateUserStateResponse\"\x00\x12?\n" +
	"\n" +
	"DeleteUser\x12\x16.pbx.DeleteUserRequest\x1a\x17.pbx.DeleteUserResponse\"\x00\x12N\n" +
	"\x0fCreateGroupChat\x12\x1b.pbx.CreateGroupChatRequest\x1a\x1c.pbx.CreateGroupChatResponse\"\x00B]\n" +
	"\acom.pbxB\n" +
	"AdminProtoP\x01Z\x1agithub.com/tinode/chat/pbx\xa2\x02\x03PXX\xaa\x02\x03Pbx\xca\x02\x03Pbx\xe2\x02\x0fPbx\\GPBMetadata\xea\x02\x03Pbxb\x06proto3"

var (
	file_admin_proto_rawDescOnce sync.Once
	file_admin_proto_rawDescData []byte
)

func file_admin_proto_rawDescGZIP() []byte {
	file_admin_proto_rawDescOnce.Do(func() {
		file_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_admin_proto_rawDesc), len(file_admin_proto_rawDesc)))
	})
	return file_admin_proto_rawDescData
}

var file_admin_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_admin_proto_goTypes = []any{
	(AccountState)(0),               // 0: pbx.AccountState
	(*User)(nil),                    // 1: pbx.User
	(*MakeUserRootRequest)(nil),     // 2: pbx.MakeUserRootRequest
	(*MakeUserRootResponse)(nil),    // 3: pbx.MakeUserRootResponse
	(*GetUserRequest)(nil),          // 4: pbx.GetUserRequest
	(*UpdateUserStateRequest)(nil),  // 5: pbx.UpdateUserStateRequest
	(*UpdateUserStateResponse)(nil), // 6: pbx.UpdateUserStateResponse
	(*DeleteUserRequest)(nil),       // 7: pbx.DeleteUserRequest
	(*DeleteUserResponse)(nil),      // 8: pbx.DeleteUserResponse
	(*CreateGroupChatRequest)(nil),  // 9: pbx.CreateGroupChatRequest
	(*CreateGroupChatResponse)(nil), // 10: pbx.CreateGroupChatResponse
	(*timestamppb.Timestamp)(nil),   // 11: google.protobuf.Timestamp
}
var file_admin_proto_depIdxs = []int32{
	11, // 0: pbx.User.last_seen:type_name -> google.protobuf.Timestamp
	0,  // 1: pbx.UpdateUserStateRequest.state:type_name -> pbx.AccountState
	2,  // 2: pbx.AdminService.MakeUserRoot:input_type -> pbx.MakeUserRootRequest
	4,  // 3: pbx.AdminService.GetUser:input_type -> pbx.GetUserRequest
	5,  // 4: pbx.AdminService.UpdateUserState:input_type -> pbx.UpdateUserStateRequest
	7,  // 5: pbx.AdminService.DeleteUser:input_type -> pbx.DeleteUserRequest
	9,  // 6: pbx.AdminService.CreateGroupChat:input_type -> pbx.CreateGroupChatRequest
	3,  // 7: pbx.AdminService.MakeUserRoot:output_type -> pbx.MakeUserRootResponse
	1,  // 8: pbx.AdminService.GetUser:output_type -> pbx.User
	6,  // 9: pbx.AdminService.UpdateUserState:output_type -> pbx.UpdateUserStateResponse
	8,  // 10: pbx.AdminService.DeleteUser:output_type -> pbx.DeleteUserResponse
	10, // 11: pbx.AdminService.CreateGroupChat:output_type -> pbx.CreateGroupChatResponse
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_admin_proto_init() }
func file_admin_proto_init() {
	if File_admin_proto != nil {
		return
	}
	file_model_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_admin_proto_rawDesc), len(file_admin_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_admin_proto_goTypes,
		DependencyIndexes: file_admin_proto_depIdxs,
		EnumInfos:         file_admin_proto_enumTypes,
		MessageInfos:      file_admin_proto_msgTypes,
	}.Build()
	File_admin_proto = out.File
	file_admin_proto_goTypes = nil
	file_admin_proto_depIdxs = nil
}
