//
// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the protocol buffer compiler.
// Source: admin.proto
//
import GRPC
import NIO
import NIOConcurrencyHelpers
import SwiftProtobuf


/// AdminService provides administrative functionality for managing the Tinode server.
///
/// Usage: instantiate `Pbx_AdminServiceClient`, then call methods of this protocol to make API calls.
public protocol Pbx_AdminServiceClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: Pbx_AdminServiceClientInterceptorFactoryProtocol? { get }

  func makeUserRoot(
    _ request: Pbx_MakeUserRootRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Pbx_MakeUserRootRequest, Pbx_MakeUserRootResponse>

  func getUser(
    _ request: Pbx_GetUserRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Pbx_GetUserRequest, Pbx_User>

  func updateUserState(
    _ request: Pbx_UpdateUserStateRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Pbx_UpdateUserStateRequest, Pbx_UpdateUserStateResponse>

  func deleteUser(
    _ request: Pbx_DeleteUserRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Pbx_DeleteUserRequest, Pbx_DeleteUserResponse>

  func createGroupChat(
    _ request: Pbx_CreateGroupChatRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Pbx_CreateGroupChatRequest, Pbx_CreateGroupChatResponse>
}

extension Pbx_AdminServiceClientProtocol {
  public var serviceName: String {
    return "pbx.AdminService"
  }

  /// MakeUserRoot changes a user's authentication level to ROOT.
  ///
  /// - Parameters:
  ///   - request: Request to send to MakeUserRoot.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func makeUserRoot(
    _ request: Pbx_MakeUserRootRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Pbx_MakeUserRootRequest, Pbx_MakeUserRootResponse> {
    return self.makeUnaryCall(
      path: Pbx_AdminServiceClientMetadata.Methods.makeUserRoot.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeMakeUserRootInterceptors() ?? []
    )
  }

  /// GetUser retrieves detailed information about a user.
  ///
  /// - Parameters:
  ///   - request: Request to send to GetUser.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func getUser(
    _ request: Pbx_GetUserRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Pbx_GetUserRequest, Pbx_User> {
    return self.makeUnaryCall(
      path: Pbx_AdminServiceClientMetadata.Methods.getUser.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetUserInterceptors() ?? []
    )
  }

  /// UpdateUserState changes a user's account state (normal, suspended).
  ///
  /// - Parameters:
  ///   - request: Request to send to UpdateUserState.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func updateUserState(
    _ request: Pbx_UpdateUserStateRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Pbx_UpdateUserStateRequest, Pbx_UpdateUserStateResponse> {
    return self.makeUnaryCall(
      path: Pbx_AdminServiceClientMetadata.Methods.updateUserState.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeUpdateUserStateInterceptors() ?? []
    )
  }

  /// DeleteUser permanently removes a user account.
  ///
  /// - Parameters:
  ///   - request: Request to send to DeleteUser.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func deleteUser(
    _ request: Pbx_DeleteUserRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Pbx_DeleteUserRequest, Pbx_DeleteUserResponse> {
    return self.makeUnaryCall(
      path: Pbx_AdminServiceClientMetadata.Methods.deleteUser.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeDeleteUserInterceptors() ?? []
    )
  }

  /// CreateGroupChat creates a new group chat on behalf of a user.
  /// Note that the user do not subscribe to the topic by default
  ///
  /// - Parameters:
  ///   - request: Request to send to CreateGroupChat.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func createGroupChat(
    _ request: Pbx_CreateGroupChatRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Pbx_CreateGroupChatRequest, Pbx_CreateGroupChatResponse> {
    return self.makeUnaryCall(
      path: Pbx_AdminServiceClientMetadata.Methods.createGroupChat.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeCreateGroupChatInterceptors() ?? []
    )
  }
}

@available(*, deprecated)
extension Pbx_AdminServiceClient: @unchecked Sendable {}

@available(*, deprecated, renamed: "Pbx_AdminServiceNIOClient")
public final class Pbx_AdminServiceClient: Pbx_AdminServiceClientProtocol {
  private let lock = Lock()
  private var _defaultCallOptions: CallOptions
  private var _interceptors: Pbx_AdminServiceClientInterceptorFactoryProtocol?
  public let channel: GRPCChannel
  public var defaultCallOptions: CallOptions {
    get { self.lock.withLock { return self._defaultCallOptions } }
    set { self.lock.withLockVoid { self._defaultCallOptions = newValue } }
  }
  public var interceptors: Pbx_AdminServiceClientInterceptorFactoryProtocol? {
    get { self.lock.withLock { return self._interceptors } }
    set { self.lock.withLockVoid { self._interceptors = newValue } }
  }

  /// Creates a client for the pbx.AdminService service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Pbx_AdminServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self._defaultCallOptions = defaultCallOptions
    self._interceptors = interceptors
  }
}

public struct Pbx_AdminServiceNIOClient: Pbx_AdminServiceClientProtocol {
  public var channel: GRPCChannel
  public var defaultCallOptions: CallOptions
  public var interceptors: Pbx_AdminServiceClientInterceptorFactoryProtocol?

  /// Creates a client for the pbx.AdminService service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Pbx_AdminServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

/// AdminService provides administrative functionality for managing the Tinode server.
@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public protocol Pbx_AdminServiceAsyncClientProtocol: GRPCClient {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Pbx_AdminServiceClientInterceptorFactoryProtocol? { get }

  func makeMakeUserRootCall(
    _ request: Pbx_MakeUserRootRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Pbx_MakeUserRootRequest, Pbx_MakeUserRootResponse>

  func makeGetUserCall(
    _ request: Pbx_GetUserRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Pbx_GetUserRequest, Pbx_User>

  func makeUpdateUserStateCall(
    _ request: Pbx_UpdateUserStateRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Pbx_UpdateUserStateRequest, Pbx_UpdateUserStateResponse>

  func makeDeleteUserCall(
    _ request: Pbx_DeleteUserRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Pbx_DeleteUserRequest, Pbx_DeleteUserResponse>

  func makeCreateGroupChatCall(
    _ request: Pbx_CreateGroupChatRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Pbx_CreateGroupChatRequest, Pbx_CreateGroupChatResponse>
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Pbx_AdminServiceAsyncClientProtocol {
  public static var serviceDescriptor: GRPCServiceDescriptor {
    return Pbx_AdminServiceClientMetadata.serviceDescriptor
  }

  public var interceptors: Pbx_AdminServiceClientInterceptorFactoryProtocol? {
    return nil
  }

  public func makeMakeUserRootCall(
    _ request: Pbx_MakeUserRootRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Pbx_MakeUserRootRequest, Pbx_MakeUserRootResponse> {
    return self.makeAsyncUnaryCall(
      path: Pbx_AdminServiceClientMetadata.Methods.makeUserRoot.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeMakeUserRootInterceptors() ?? []
    )
  }

  public func makeGetUserCall(
    _ request: Pbx_GetUserRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Pbx_GetUserRequest, Pbx_User> {
    return self.makeAsyncUnaryCall(
      path: Pbx_AdminServiceClientMetadata.Methods.getUser.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetUserInterceptors() ?? []
    )
  }

  public func makeUpdateUserStateCall(
    _ request: Pbx_UpdateUserStateRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Pbx_UpdateUserStateRequest, Pbx_UpdateUserStateResponse> {
    return self.makeAsyncUnaryCall(
      path: Pbx_AdminServiceClientMetadata.Methods.updateUserState.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeUpdateUserStateInterceptors() ?? []
    )
  }

  public func makeDeleteUserCall(
    _ request: Pbx_DeleteUserRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Pbx_DeleteUserRequest, Pbx_DeleteUserResponse> {
    return self.makeAsyncUnaryCall(
      path: Pbx_AdminServiceClientMetadata.Methods.deleteUser.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeDeleteUserInterceptors() ?? []
    )
  }

  public func makeCreateGroupChatCall(
    _ request: Pbx_CreateGroupChatRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Pbx_CreateGroupChatRequest, Pbx_CreateGroupChatResponse> {
    return self.makeAsyncUnaryCall(
      path: Pbx_AdminServiceClientMetadata.Methods.createGroupChat.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeCreateGroupChatInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Pbx_AdminServiceAsyncClientProtocol {
  public func makeUserRoot(
    _ request: Pbx_MakeUserRootRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Pbx_MakeUserRootResponse {
    return try await self.performAsyncUnaryCall(
      path: Pbx_AdminServiceClientMetadata.Methods.makeUserRoot.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeMakeUserRootInterceptors() ?? []
    )
  }

  public func getUser(
    _ request: Pbx_GetUserRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Pbx_User {
    return try await self.performAsyncUnaryCall(
      path: Pbx_AdminServiceClientMetadata.Methods.getUser.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetUserInterceptors() ?? []
    )
  }

  public func updateUserState(
    _ request: Pbx_UpdateUserStateRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Pbx_UpdateUserStateResponse {
    return try await self.performAsyncUnaryCall(
      path: Pbx_AdminServiceClientMetadata.Methods.updateUserState.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeUpdateUserStateInterceptors() ?? []
    )
  }

  public func deleteUser(
    _ request: Pbx_DeleteUserRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Pbx_DeleteUserResponse {
    return try await self.performAsyncUnaryCall(
      path: Pbx_AdminServiceClientMetadata.Methods.deleteUser.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeDeleteUserInterceptors() ?? []
    )
  }

  public func createGroupChat(
    _ request: Pbx_CreateGroupChatRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Pbx_CreateGroupChatResponse {
    return try await self.performAsyncUnaryCall(
      path: Pbx_AdminServiceClientMetadata.Methods.createGroupChat.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeCreateGroupChatInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public struct Pbx_AdminServiceAsyncClient: Pbx_AdminServiceAsyncClientProtocol {
  public var channel: GRPCChannel
  public var defaultCallOptions: CallOptions
  public var interceptors: Pbx_AdminServiceClientInterceptorFactoryProtocol?

  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Pbx_AdminServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

public protocol Pbx_AdminServiceClientInterceptorFactoryProtocol: Sendable {

  /// - Returns: Interceptors to use when invoking 'makeUserRoot'.
  func makeMakeUserRootInterceptors() -> [ClientInterceptor<Pbx_MakeUserRootRequest, Pbx_MakeUserRootResponse>]

  /// - Returns: Interceptors to use when invoking 'getUser'.
  func makeGetUserInterceptors() -> [ClientInterceptor<Pbx_GetUserRequest, Pbx_User>]

  /// - Returns: Interceptors to use when invoking 'updateUserState'.
  func makeUpdateUserStateInterceptors() -> [ClientInterceptor<Pbx_UpdateUserStateRequest, Pbx_UpdateUserStateResponse>]

  /// - Returns: Interceptors to use when invoking 'deleteUser'.
  func makeDeleteUserInterceptors() -> [ClientInterceptor<Pbx_DeleteUserRequest, Pbx_DeleteUserResponse>]

  /// - Returns: Interceptors to use when invoking 'createGroupChat'.
  func makeCreateGroupChatInterceptors() -> [ClientInterceptor<Pbx_CreateGroupChatRequest, Pbx_CreateGroupChatResponse>]
}

public enum Pbx_AdminServiceClientMetadata {
  public static let serviceDescriptor = GRPCServiceDescriptor(
    name: "AdminService",
    fullName: "pbx.AdminService",
    methods: [
      Pbx_AdminServiceClientMetadata.Methods.makeUserRoot,
      Pbx_AdminServiceClientMetadata.Methods.getUser,
      Pbx_AdminServiceClientMetadata.Methods.updateUserState,
      Pbx_AdminServiceClientMetadata.Methods.deleteUser,
      Pbx_AdminServiceClientMetadata.Methods.createGroupChat,
    ]
  )

  public enum Methods {
    public static let makeUserRoot = GRPCMethodDescriptor(
      name: "MakeUserRoot",
      path: "/pbx.AdminService/MakeUserRoot",
      type: GRPCCallType.unary
    )

    public static let getUser = GRPCMethodDescriptor(
      name: "GetUser",
      path: "/pbx.AdminService/GetUser",
      type: GRPCCallType.unary
    )

    public static let updateUserState = GRPCMethodDescriptor(
      name: "UpdateUserState",
      path: "/pbx.AdminService/UpdateUserState",
      type: GRPCCallType.unary
    )

    public static let deleteUser = GRPCMethodDescriptor(
      name: "DeleteUser",
      path: "/pbx.AdminService/DeleteUser",
      type: GRPCCallType.unary
    )

    public static let createGroupChat = GRPCMethodDescriptor(
      name: "CreateGroupChat",
      path: "/pbx.AdminService/CreateGroupChat",
      type: GRPCCallType.unary
    )
  }
}

