//
// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the protocol buffer compiler.
// Source: model.proto
//
import GRPC
import NIO
import NIOConcurrencyHelpers
import SwiftProtobuf


/// This is the single method that needs to be implemented by a gRPC client.
///
/// Usage: instantiate `Pbx_NodeClient`, then call methods of this protocol to make API calls.
public protocol Pbx_NodeClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: Pbx_NodeClientInterceptorFactoryProtocol? { get }

  func messageLoop(
    callOptions: CallOptions?,
    handler: @escaping (Pbx_ServerMsg) -> Void
  ) -> BidirectionalStreamingCall<Pbx_ClientMsg, Pbx_ServerMsg>
}

extension Pbx_NodeClientProtocol {
  public var serviceName: String {
    return "pbx.Node"
  }

  /// Client sends a stream of ClientMsg, server responds with a stream of ServerMsg
  ///
  /// Callers should use the `send` method on the returned object to send messages
  /// to the server. The caller should send an `.end` after the final message has been sent.
  ///
  /// - Parameters:
  ///   - callOptions: Call options.
  ///   - handler: A closure called when each response is received from the server.
  /// - Returns: A `ClientStreamingCall` with futures for the metadata and status.
  public func messageLoop(
    callOptions: CallOptions? = nil,
    handler: @escaping (Pbx_ServerMsg) -> Void
  ) -> BidirectionalStreamingCall<Pbx_ClientMsg, Pbx_ServerMsg> {
    return self.makeBidirectionalStreamingCall(
      path: Pbx_NodeClientMetadata.Methods.messageLoop.path,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeMessageLoopInterceptors() ?? [],
      handler: handler
    )
  }
}

@available(*, deprecated)
extension Pbx_NodeClient: @unchecked Sendable {}

@available(*, deprecated, renamed: "Pbx_NodeNIOClient")
public final class Pbx_NodeClient: Pbx_NodeClientProtocol {
  private let lock = Lock()
  private var _defaultCallOptions: CallOptions
  private var _interceptors: Pbx_NodeClientInterceptorFactoryProtocol?
  public let channel: GRPCChannel
  public var defaultCallOptions: CallOptions {
    get { self.lock.withLock { return self._defaultCallOptions } }
    set { self.lock.withLockVoid { self._defaultCallOptions = newValue } }
  }
  public var interceptors: Pbx_NodeClientInterceptorFactoryProtocol? {
    get { self.lock.withLock { return self._interceptors } }
    set { self.lock.withLockVoid { self._interceptors = newValue } }
  }

  /// Creates a client for the pbx.Node service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Pbx_NodeClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self._defaultCallOptions = defaultCallOptions
    self._interceptors = interceptors
  }
}

public struct Pbx_NodeNIOClient: Pbx_NodeClientProtocol {
  public var channel: GRPCChannel
  public var defaultCallOptions: CallOptions
  public var interceptors: Pbx_NodeClientInterceptorFactoryProtocol?

  /// Creates a client for the pbx.Node service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Pbx_NodeClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

/// This is the single method that needs to be implemented by a gRPC client.
@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public protocol Pbx_NodeAsyncClientProtocol: GRPCClient {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Pbx_NodeClientInterceptorFactoryProtocol? { get }

  func makeMessageLoopCall(
    callOptions: CallOptions?
  ) -> GRPCAsyncBidirectionalStreamingCall<Pbx_ClientMsg, Pbx_ServerMsg>
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Pbx_NodeAsyncClientProtocol {
  public static var serviceDescriptor: GRPCServiceDescriptor {
    return Pbx_NodeClientMetadata.serviceDescriptor
  }

  public var interceptors: Pbx_NodeClientInterceptorFactoryProtocol? {
    return nil
  }

  public func makeMessageLoopCall(
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncBidirectionalStreamingCall<Pbx_ClientMsg, Pbx_ServerMsg> {
    return self.makeAsyncBidirectionalStreamingCall(
      path: Pbx_NodeClientMetadata.Methods.messageLoop.path,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeMessageLoopInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Pbx_NodeAsyncClientProtocol {
  public func messageLoop<RequestStream>(
    _ requests: RequestStream,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncResponseStream<Pbx_ServerMsg> where RequestStream: Sequence, RequestStream.Element == Pbx_ClientMsg {
    return self.performAsyncBidirectionalStreamingCall(
      path: Pbx_NodeClientMetadata.Methods.messageLoop.path,
      requests: requests,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeMessageLoopInterceptors() ?? []
    )
  }

  public func messageLoop<RequestStream>(
    _ requests: RequestStream,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncResponseStream<Pbx_ServerMsg> where RequestStream: AsyncSequence & Sendable, RequestStream.Element == Pbx_ClientMsg {
    return self.performAsyncBidirectionalStreamingCall(
      path: Pbx_NodeClientMetadata.Methods.messageLoop.path,
      requests: requests,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeMessageLoopInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public struct Pbx_NodeAsyncClient: Pbx_NodeAsyncClientProtocol {
  public var channel: GRPCChannel
  public var defaultCallOptions: CallOptions
  public var interceptors: Pbx_NodeClientInterceptorFactoryProtocol?

  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Pbx_NodeClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

public protocol Pbx_NodeClientInterceptorFactoryProtocol: Sendable {

  /// - Returns: Interceptors to use when invoking 'messageLoop'.
  func makeMessageLoopInterceptors() -> [ClientInterceptor<Pbx_ClientMsg, Pbx_ServerMsg>]
}

public enum Pbx_NodeClientMetadata {
  public static let serviceDescriptor = GRPCServiceDescriptor(
    name: "Node",
    fullName: "pbx.Node",
    methods: [
      Pbx_NodeClientMetadata.Methods.messageLoop,
    ]
  )

  public enum Methods {
    public static let messageLoop = GRPCMethodDescriptor(
      name: "MessageLoop",
      path: "/pbx.Node/MessageLoop",
      type: GRPCCallType.bidirectionalStreaming
    )
  }
}

/// Plugin interface.
///
/// Usage: instantiate `Pbx_PluginClient`, then call methods of this protocol to make API calls.
public protocol Pbx_PluginClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: Pbx_PluginClientInterceptorFactoryProtocol? { get }

  func fireHose(
    _ request: Pbx_ClientReq,
    callOptions: CallOptions?
  ) -> UnaryCall<Pbx_ClientReq, Pbx_ServerResp>

  func find(
    _ request: Pbx_SearchQuery,
    callOptions: CallOptions?
  ) -> UnaryCall<Pbx_SearchQuery, Pbx_SearchFound>

  func account(
    _ request: Pbx_AccountEvent,
    callOptions: CallOptions?
  ) -> UnaryCall<Pbx_AccountEvent, Pbx_Unused>

  func topic(
    _ request: Pbx_TopicEvent,
    callOptions: CallOptions?
  ) -> UnaryCall<Pbx_TopicEvent, Pbx_Unused>

  func subscription(
    _ request: Pbx_SubscriptionEvent,
    callOptions: CallOptions?
  ) -> UnaryCall<Pbx_SubscriptionEvent, Pbx_Unused>

  func message(
    _ request: Pbx_MessageEvent,
    callOptions: CallOptions?
  ) -> UnaryCall<Pbx_MessageEvent, Pbx_Unused>
}

extension Pbx_PluginClientProtocol {
  public var serviceName: String {
    return "pbx.Plugin"
  }

  /// This plugin method is called by Tinode server for every message received from the clients. The
  /// method returns a ServerCtrl message. Non-zero ServerCtrl.code indicates that no further
  /// processing is needed. The Tinode server will generate a {ctrl} message from the returned ServerCtrl
  /// and forward it to the client session.
  /// ServerCtrl.code equals to 0 instructs the server to continue with default processing of the client message.
  ///
  /// - Parameters:
  ///   - request: Request to send to FireHose.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func fireHose(
    _ request: Pbx_ClientReq,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Pbx_ClientReq, Pbx_ServerResp> {
    return self.makeUnaryCall(
      path: Pbx_PluginClientMetadata.Methods.fireHose.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeFireHoseInterceptors() ?? []
    )
  }

  /// An alteranative user and topic discovery mechanism.
  /// A search request issued on a 'fnd' topic. This method is called to generate an alternative result set.
  ///
  /// - Parameters:
  ///   - request: Request to send to Find.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func find(
    _ request: Pbx_SearchQuery,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Pbx_SearchQuery, Pbx_SearchFound> {
    return self.makeUnaryCall(
      path: Pbx_PluginClientMetadata.Methods.find.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeFindInterceptors() ?? []
    )
  }

  /// Account created, updated or deleted
  ///
  /// - Parameters:
  ///   - request: Request to send to Account.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func account(
    _ request: Pbx_AccountEvent,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Pbx_AccountEvent, Pbx_Unused> {
    return self.makeUnaryCall(
      path: Pbx_PluginClientMetadata.Methods.account.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeAccountInterceptors() ?? []
    )
  }

  /// Topic created, updated [or deleted -- not supported yet]
  ///
  /// - Parameters:
  ///   - request: Request to send to Topic.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func topic(
    _ request: Pbx_TopicEvent,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Pbx_TopicEvent, Pbx_Unused> {
    return self.makeUnaryCall(
      path: Pbx_PluginClientMetadata.Methods.topic.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeTopicInterceptors() ?? []
    )
  }

  /// Subscription created, updated or deleted
  ///
  /// - Parameters:
  ///   - request: Request to send to Subscription.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func subscription(
    _ request: Pbx_SubscriptionEvent,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Pbx_SubscriptionEvent, Pbx_Unused> {
    return self.makeUnaryCall(
      path: Pbx_PluginClientMetadata.Methods.subscription.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeSubscriptionInterceptors() ?? []
    )
  }

  /// Message published or deleted
  ///
  /// - Parameters:
  ///   - request: Request to send to Message.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func message(
    _ request: Pbx_MessageEvent,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Pbx_MessageEvent, Pbx_Unused> {
    return self.makeUnaryCall(
      path: Pbx_PluginClientMetadata.Methods.message.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeMessageInterceptors() ?? []
    )
  }
}

@available(*, deprecated)
extension Pbx_PluginClient: @unchecked Sendable {}

@available(*, deprecated, renamed: "Pbx_PluginNIOClient")
public final class Pbx_PluginClient: Pbx_PluginClientProtocol {
  private let lock = Lock()
  private var _defaultCallOptions: CallOptions
  private var _interceptors: Pbx_PluginClientInterceptorFactoryProtocol?
  public let channel: GRPCChannel
  public var defaultCallOptions: CallOptions {
    get { self.lock.withLock { return self._defaultCallOptions } }
    set { self.lock.withLockVoid { self._defaultCallOptions = newValue } }
  }
  public var interceptors: Pbx_PluginClientInterceptorFactoryProtocol? {
    get { self.lock.withLock { return self._interceptors } }
    set { self.lock.withLockVoid { self._interceptors = newValue } }
  }

  /// Creates a client for the pbx.Plugin service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Pbx_PluginClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self._defaultCallOptions = defaultCallOptions
    self._interceptors = interceptors
  }
}

public struct Pbx_PluginNIOClient: Pbx_PluginClientProtocol {
  public var channel: GRPCChannel
  public var defaultCallOptions: CallOptions
  public var interceptors: Pbx_PluginClientInterceptorFactoryProtocol?

  /// Creates a client for the pbx.Plugin service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Pbx_PluginClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

/// Plugin interface.
@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public protocol Pbx_PluginAsyncClientProtocol: GRPCClient {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Pbx_PluginClientInterceptorFactoryProtocol? { get }

  func makeFireHoseCall(
    _ request: Pbx_ClientReq,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Pbx_ClientReq, Pbx_ServerResp>

  func makeFindCall(
    _ request: Pbx_SearchQuery,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Pbx_SearchQuery, Pbx_SearchFound>

  func makeAccountCall(
    _ request: Pbx_AccountEvent,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Pbx_AccountEvent, Pbx_Unused>

  func makeTopicCall(
    _ request: Pbx_TopicEvent,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Pbx_TopicEvent, Pbx_Unused>

  func makeSubscriptionCall(
    _ request: Pbx_SubscriptionEvent,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Pbx_SubscriptionEvent, Pbx_Unused>

  func makeMessageCall(
    _ request: Pbx_MessageEvent,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Pbx_MessageEvent, Pbx_Unused>
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Pbx_PluginAsyncClientProtocol {
  public static var serviceDescriptor: GRPCServiceDescriptor {
    return Pbx_PluginClientMetadata.serviceDescriptor
  }

  public var interceptors: Pbx_PluginClientInterceptorFactoryProtocol? {
    return nil
  }

  public func makeFireHoseCall(
    _ request: Pbx_ClientReq,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Pbx_ClientReq, Pbx_ServerResp> {
    return self.makeAsyncUnaryCall(
      path: Pbx_PluginClientMetadata.Methods.fireHose.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeFireHoseInterceptors() ?? []
    )
  }

  public func makeFindCall(
    _ request: Pbx_SearchQuery,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Pbx_SearchQuery, Pbx_SearchFound> {
    return self.makeAsyncUnaryCall(
      path: Pbx_PluginClientMetadata.Methods.find.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeFindInterceptors() ?? []
    )
  }

  public func makeAccountCall(
    _ request: Pbx_AccountEvent,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Pbx_AccountEvent, Pbx_Unused> {
    return self.makeAsyncUnaryCall(
      path: Pbx_PluginClientMetadata.Methods.account.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeAccountInterceptors() ?? []
    )
  }

  public func makeTopicCall(
    _ request: Pbx_TopicEvent,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Pbx_TopicEvent, Pbx_Unused> {
    return self.makeAsyncUnaryCall(
      path: Pbx_PluginClientMetadata.Methods.topic.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeTopicInterceptors() ?? []
    )
  }

  public func makeSubscriptionCall(
    _ request: Pbx_SubscriptionEvent,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Pbx_SubscriptionEvent, Pbx_Unused> {
    return self.makeAsyncUnaryCall(
      path: Pbx_PluginClientMetadata.Methods.subscription.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeSubscriptionInterceptors() ?? []
    )
  }

  public func makeMessageCall(
    _ request: Pbx_MessageEvent,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Pbx_MessageEvent, Pbx_Unused> {
    return self.makeAsyncUnaryCall(
      path: Pbx_PluginClientMetadata.Methods.message.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeMessageInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Pbx_PluginAsyncClientProtocol {
  public func fireHose(
    _ request: Pbx_ClientReq,
    callOptions: CallOptions? = nil
  ) async throws -> Pbx_ServerResp {
    return try await self.performAsyncUnaryCall(
      path: Pbx_PluginClientMetadata.Methods.fireHose.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeFireHoseInterceptors() ?? []
    )
  }

  public func find(
    _ request: Pbx_SearchQuery,
    callOptions: CallOptions? = nil
  ) async throws -> Pbx_SearchFound {
    return try await self.performAsyncUnaryCall(
      path: Pbx_PluginClientMetadata.Methods.find.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeFindInterceptors() ?? []
    )
  }

  public func account(
    _ request: Pbx_AccountEvent,
    callOptions: CallOptions? = nil
  ) async throws -> Pbx_Unused {
    return try await self.performAsyncUnaryCall(
      path: Pbx_PluginClientMetadata.Methods.account.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeAccountInterceptors() ?? []
    )
  }

  public func topic(
    _ request: Pbx_TopicEvent,
    callOptions: CallOptions? = nil
  ) async throws -> Pbx_Unused {
    return try await self.performAsyncUnaryCall(
      path: Pbx_PluginClientMetadata.Methods.topic.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeTopicInterceptors() ?? []
    )
  }

  public func subscription(
    _ request: Pbx_SubscriptionEvent,
    callOptions: CallOptions? = nil
  ) async throws -> Pbx_Unused {
    return try await self.performAsyncUnaryCall(
      path: Pbx_PluginClientMetadata.Methods.subscription.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeSubscriptionInterceptors() ?? []
    )
  }

  public func message(
    _ request: Pbx_MessageEvent,
    callOptions: CallOptions? = nil
  ) async throws -> Pbx_Unused {
    return try await self.performAsyncUnaryCall(
      path: Pbx_PluginClientMetadata.Methods.message.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeMessageInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public struct Pbx_PluginAsyncClient: Pbx_PluginAsyncClientProtocol {
  public var channel: GRPCChannel
  public var defaultCallOptions: CallOptions
  public var interceptors: Pbx_PluginClientInterceptorFactoryProtocol?

  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Pbx_PluginClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

public protocol Pbx_PluginClientInterceptorFactoryProtocol: Sendable {

  /// - Returns: Interceptors to use when invoking 'fireHose'.
  func makeFireHoseInterceptors() -> [ClientInterceptor<Pbx_ClientReq, Pbx_ServerResp>]

  /// - Returns: Interceptors to use when invoking 'find'.
  func makeFindInterceptors() -> [ClientInterceptor<Pbx_SearchQuery, Pbx_SearchFound>]

  /// - Returns: Interceptors to use when invoking 'account'.
  func makeAccountInterceptors() -> [ClientInterceptor<Pbx_AccountEvent, Pbx_Unused>]

  /// - Returns: Interceptors to use when invoking 'topic'.
  func makeTopicInterceptors() -> [ClientInterceptor<Pbx_TopicEvent, Pbx_Unused>]

  /// - Returns: Interceptors to use when invoking 'subscription'.
  func makeSubscriptionInterceptors() -> [ClientInterceptor<Pbx_SubscriptionEvent, Pbx_Unused>]

  /// - Returns: Interceptors to use when invoking 'message'.
  func makeMessageInterceptors() -> [ClientInterceptor<Pbx_MessageEvent, Pbx_Unused>]
}

public enum Pbx_PluginClientMetadata {
  public static let serviceDescriptor = GRPCServiceDescriptor(
    name: "Plugin",
    fullName: "pbx.Plugin",
    methods: [
      Pbx_PluginClientMetadata.Methods.fireHose,
      Pbx_PluginClientMetadata.Methods.find,
      Pbx_PluginClientMetadata.Methods.account,
      Pbx_PluginClientMetadata.Methods.topic,
      Pbx_PluginClientMetadata.Methods.subscription,
      Pbx_PluginClientMetadata.Methods.message,
    ]
  )

  public enum Methods {
    public static let fireHose = GRPCMethodDescriptor(
      name: "FireHose",
      path: "/pbx.Plugin/FireHose",
      type: GRPCCallType.unary
    )

    public static let find = GRPCMethodDescriptor(
      name: "Find",
      path: "/pbx.Plugin/Find",
      type: GRPCCallType.unary
    )

    public static let account = GRPCMethodDescriptor(
      name: "Account",
      path: "/pbx.Plugin/Account",
      type: GRPCCallType.unary
    )

    public static let topic = GRPCMethodDescriptor(
      name: "Topic",
      path: "/pbx.Plugin/Topic",
      type: GRPCCallType.unary
    )

    public static let subscription = GRPCMethodDescriptor(
      name: "Subscription",
      path: "/pbx.Plugin/Subscription",
      type: GRPCCallType.unary
    )

    public static let message = GRPCMethodDescriptor(
      name: "Message",
      path: "/pbx.Plugin/Message",
      type: GRPCCallType.unary
    )
  }
}

